version: "3"

services:
  db:
    image: postgres:13-alpine
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    command: ["cd", "alembic", "alembic", "upgrade", "head"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    working_dir: /code/

volumes:
  postgres-data:
